# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Groepspraktijk Vos
email: steffievoslogo@hotmail.be
description: > # this means to ignore newlines until "baseurl:"
  Groepspraktijk Vos : logopedie, kinesitherapie, psychomotoriek, diëtetiek, life coaching, typ10 & zomercursussen voor kinderen te Sint-Katelijne-Waver.
  Wie werkt hieraan mee: Steffie Vos, Laurien Heylen, Joke Vonckx, Eline Holvoet & Jago Crol.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://groepspraktijkvos.be" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
markdown: kramdown
destination: public
exclude: ["Rakefile", "README.md", "public", "jekyll", "Gemfile", "Guardfile","bower_components/base/changelog.html","bower_components/base/dist/index.html","bower_components/base/src/index.html","bower_components/picturefill/index.html","bower_components/Ionicons/index.html"]

plugins:
  - jekyll-sitemap
